export const STORAGE_KEYS = {
  profile: '@forge/profile',
  meals: '@forge/meals',
  water: '@forge/water',
  workouts: '@forge/workouts',
  programProgress: '@forge/program-progress',
  customWorkouts: '@forge/custom-workouts',
  notifications: '@forge/notification-preferences',
  exerciseFavorites: '@forge/exercise-favorites',
  mealTemplates: '@forge/meal-templates',
  mealTemplateFavorites: '@forge/meal-template-favorites',
  dismissedMealTemplates: '@forge/dismissed-meal-templates',
  waterPreferences: '@forge/water-preferences',
  activeWorkoutSession: '@forge/active-workout-session',
  preferences: '@forge/preferences',
  aiHubAccess: '@forge/ai-hub-access',
  rewardedCredits: '@forge/rewarded-credits',
  cycleTracking: '@forge/cycle-tracking',
  coachPreferences: '@forge/coach-preferences',
  aiProgramPhysiqueSeed: '@forge/ai-program-physique-seed',
  aiProgramInstances: '@forge/ai-program-instances',
  aiProgramFeedback: '@forge/ai-program-feedback',
  userPrograms: '@forge/user-programs',
  programFavorites: '@forge/program-favorites',
} as const;

export type StorageRegistryKey = keyof typeof STORAGE_KEYS;

export const STORAGE_LABELS: Record<StorageRegistryKey, string> = {
  profile: 'Profil',
  meals: 'Öğün kayıtları',
  water: 'Su takibi',
  workouts: 'Antrenman kayıtları',
  programProgress: 'Program ilerlemesi',
  customWorkouts: 'Antrenmanım',
  notifications: 'Bildirim tercihleri',
  exerciseFavorites: 'Favori egzersizler',
  mealTemplates: 'Kaydedilen öğün şablonları',
  mealTemplateFavorites: 'Favori öğün şablonları',
  dismissedMealTemplates: 'Gizlenen öğün şablonları',
  waterPreferences: 'Su hedefi',
  activeWorkoutSession: 'Yarım kalan antrenman',
  preferences: 'Bölge ve birim tercihleri',
  aiHubAccess: 'AI Hub erişim durumu',
  rewardedCredits: 'Ödüllü reklam kredileri',
  cycleTracking: 'Döngü takibi',
  coachPreferences: 'Kişisel koç tercihleri',
  aiProgramPhysiqueSeed: 'AI program fizik aktarımı',
  aiProgramInstances: 'Kayıtlı AI programları',
  aiProgramFeedback: 'AI seans geri bildirimleri',
  userPrograms: 'Kullanıcı programları',
  programFavorites: 'Favori programlar',
};
